### ISSUE TITLE
Process View - UI

### ISSUE THREAD

**Issue by jj2021** [TiNewman/LinuxMetricsCollector#10]
Create a simple dashboard view to display a list of processes and related metrics.
Requirements:
- Table of processes 
- Display CPU utilization, RAM utilization, PID, process name and status

**Comment by JordanMurray2** [comment]
Started basic outline of template, just need to populate view with data

**Comment by JordanMurray2** [comment]
Data is being displayed, need to fix styling on table so it is compatible with different screen sizes and browsers

**Comment by JordanMurray2** [comment]
UI styling for process List is complete
