### ISSUE TITLE
Set Up Collector Database

### ISSUE THREAD

**Issue by jj2021** [TiNewman/LinuxMetricsCollector#3]
Create a new database server for storing collected system metrics.

**Comment by TiNewman** [comment]
![image](https://user-images.githubusercontent.com/31543695/155592985-06dfa03d-0e0e-46dd-98d4-431345b54621.png)

As we can see here, for now there are no history tables.
PROCESS table also has 'name' added.
In COLLECTOR, 'timeCollected' is in DATETIME2 format!

**Comment by TiNewman** [comment]
If we are going to use 'custom' query builders, and not a bunch of predefined functions, then I should have an extra function that allows for "NEWEST" search inside of these builders.
Ex: 
1. getProcessesByCustomFloatField("diskUsage", 99.99) --> Get all, even if old.
2. getProcessesNewByCustomFloatField("diskUsage", 99.99) --> Get only newest just added.
