### ISSUE TITLE
Multiple Websocket Connections From Client

### ISSUE THREAD

**Issue by jj2021** [TiNewman/LinuxMetricsCollector#30]
When using the menu on the GUI interface to switch between dashboards, the current connection is not closed. This leads to multiple connections being open and data inconsistency between the GUI and the database.

Proposed Fix:
Ensure that when the user leaves a dashboard page via the menu, the websocket connection properly closes.

**Comment by JordanMurray2** [comment]
Bug is fixed on index page, just needs to be applied to the rest of the pages

**Comment by JordanMurray2** [comment]
fix has been applied across the application. bug is fixed.
